save_root: "results/step50000_batch_20260316/"
task_name: "__all__"
start_from_task: ""
render_freq: 0
test_num: 5

policy_name: "ACT"
task_config: "demo_clean"
train_config_name: 0
model_name: 0
seed: 0
gpu_id: 0
port: 29056

video_guidance_scale: 5
action_guidance_scale: 1
